### ISSUE TITLE
Use meaningful layouts

### ISSUE THREAD

**Issue by pjotrsavitski** [centre-for-educational-technology/DTILabs#3]
Most of the pages include full HTML portion as content: head, body, header, footer and much more.

That should not be the case. If some portions should be configurable (include or not), then variables should be used as part of the page data (YAML).

In case some additional elements (like styles or scripts) should be allowed for inclusion, it should either be allowed as an injectable or some other approach is to be found.

**Comment by RolandRP** [comment]
Most of the pages are not finished yet. We started out with plain html and css and then migrated to correct formats for using Liquid and Yaml. This is still something we need to keep doing. But before that we would love to finish the designing process and then move on to functional compatibility.

**Comment by pjotrsavitski** [comment]
It does not really mean that every page has to have the full HTML inside of it. Making a layout, using it in at least one of the pages and slowly moving all the others to that should be beneficial.

The layout could be extended in order to solve issues and needs of all the other pages (multiple layouts could also be created).

The JS and CSS files issue could be solved by adding those to the YAML data header. A piece of code within the template could check if current page object has that attribute and traverse through the items adding those accordingly.

```yaml
layout: page-master
permalink: /some/sub/page
title: "Titles are also variables"
scripts:
  - main.js
  - page-specific.js
  - https://and-even-external/script.js
styles:
  - pretty-much-the-same.css
```

This should be a valid YAML file. Parsed page data should be accessible as `page.styles`
